name: Docker Image CI

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Authenticate to GCR
        env:
          GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_ACTIONS_SECRET_B64 }}
        run: |
          echo "${GCP_SERVICE_ACCOUNT_KEY}" | gcloud auth activate-service-account --key-file=-
          gcloud --quiet auth configure-docker

      - name: Build Docker image
        run: |
          SHORT_COMMIT_SHA=$(git rev-parse --short ${{ github.sha }})
          docker build -t ghcr.io/vanja-s/fun7:${SHORT_COMMIT_SHA} .

      - name: Push Docker image
        run: |
          SHORT_COMMIT_SHA=$(git rev-parse --short ${{ github.sha }})
          docker push gcr.io/compact-marker-434520-k0/fun7-cts:${SHORT_COMMIT_SHA}